### ISSUE TITLE
max 1000 files in splited raw? and begin /w .000 or .001? thx

### ISSUE THREAD

**Issue by ccchan234** [ArsenalRecon/Arsenal-Image-Mounter#12]
hi

i got HDDs of 2TB and 4TB,
i wanna make splited raw images for easy handling.

but
1. not sure shd I begin the series with .000 or .001,
AIM ask for .001 as splited raw images, yet SOME OTHER
programs do ask for .000 as the 1st part.

STRANGE thing is, if I got files of image.000 to .014, each of 1GB,
when I mount inside AIM, it shows 15GB.
i.e. the .000 is included in the collection, but AIM ask for .001...

2. 
i tried AIM only recognize .000 to .999,
it wont recognize .1000 etc.

this make my 4TB/1000 = 4GB which is a quite large file.
I prefer to have 1-2GB/file, which makes upload/download
to cloud easier.

how about alphebets? if yes, how should I include in the series?
thanks

btw, AIM seems don't have a locking mechanism,
when the drive is mounted, files copying/writing,
a simple click in AIM can "remove"the drive,
which is less prefer-ed these days I think.

thank you.

**Comment by LTRData** [comment]
Split image names can begin with either of 000 or 001. The suggestion is 001, because I think that is the most commonly used first extension for split files, but I realize it could be confusing to point to the .001 file to mount a series of files that start with .000. Maybe we will reconsider this decision at some point.

Also, the number of digits in the extension cannot change between the files. To use more than 999 files, you would either need to name the files .0001, .0002 etc, or use alphabet like .999, .A00, .A01 or something similar. As long as it is an extension with the same number of characters and that sorts by ASCII values in the order they are supposed to be used, it should work.

About locking mechanism, most recent versions of AIM GUI should display a warning first if a device in use is about to be removed.
