### ISSUE TITLE
AIM fail to mount splited raw of .0000 etc, and did AIM touch .000 file?

### ISSUE THREAD

**Issue by ccchan234** [ArsenalRecon/Arsenal-Image-Mounter#13]
hi

1. I created empty blank raw image files by win10+cygwin,
by:
dd if=/dev/zero of=(anyname).img.0000 bs=1G count=2 

thus each is 2GB file.

then i simply use batch to duplicate them into around 1000 files for 2TB HDD,
i have to use renamer say BRU to tune the file name, as in Fig-0.
ending in .0000, .0001 etc

then I open AIM, it didn't recognize .0000 or .0001 by default,
and I manually choose .0000 as the file,
AIM asked if treat as raw, ofcoz I say yes.
Then result is FIg-1: only 2GB

Then I give AIM another shot,
choosing .0001 as the file, and as in Fig-2, it's still 2GB in total.

HOWEVER, I am able to use Hex in the numbering,
so for 3alphabets, max is FFF, i.e. 4096 files.
each of 1-2GB, fits my need of 4TB to 8TB HDD.

2. IMPORANT: did AIM touch .000 file?

as asked in previous issue,
Currently I WILL include a .000 in the collection, say for some reason.  
it's STRANGE that if i got disk.000 disk.001 ... disk.014, each of 1GB,
if i open in AIM, choosing the .001 as the file,
the outcome is a 15GB disk,
which mean the disk.000 is included in the collection by AIM.

It is an ESSENTIAL question for this. becoz later I may use some rescue softwares
like , say getdataback etc for it and suppose GDB start with .000.

case 1: IF AIM DO touch .000,
then I think it's fine,
so both AIM and GDB start from .000, 
and likely will find the MBR etc (I am a layman, not programmer),
in .000. Perfect.

case 2: IF AIM DONOT touch .000
then there is a risk for me and I wanna seek HELP.
so in this case, AIM start with .001, I suppose MBR is put in .001 then?
What if I use GDB to load from .000? will GDB think (as .000 is untouched,
it is all 00) the whole collection is a BLANK?

obviously i could manually rename the files to begin /w .001 when I
use AIM and rename them to begin /w .000 when I use GDB,
but with HEX naming, there is some chance the files are mixed up---
some file manager sort 0123456789ABCDEF (e.g. BRU) and some sort by
0ABCDEF123456789! (e.g. windows file manager)

3.  ps: how do AIM sort the 0-9 and ABCDEF? that info may help, thx

hope wont be too much of trouble by asking these.
thanks.

And everybody take care!

![0-file-list](https://user-images.githubusercontent.com/37549409/78762345-5416a380-79b6-11ea-8f0e-228e7f4a7fcc.png)
![1-0000-fail](https://user-images.githubusercontent.com/37549409/78762349-5547d080-79b6-11ea-9354-638573eb3e9d.png)
![2-0001-fail](https://user-images.githubusercontent.com/37549409/78762351-55e06700-79b6-11ea-805b-1a896e2f8d5f.png)

**Comment by LTRData** [comment]
1. Any particular reason why you use dd for this? It is possible to create a new file with a specified size using fsutil. For example, to create a 2 GB file:
`fsutil file createnew file.000 2147483648`
I would think this could save you some time when creating those files. Preferably in your case, use it in a loop in a batch file instead of creating one file and copying that to other files.

2. You are right, I did not think of the GUI here. The GUI requires an extension of .001 specifically to detect a multi-part raw image. The command line version aim_cli.exe can be used to mount .0001 etc files though.
`aim_cli /mount /filename=test.0001 /provider=multipartraw`

And maybe I was not clear about it previously but yes, it will use a .000 if there is such a file. But in the GUI you would still need to point it to the .001 file to mount. It will automatically detect all files starting with .000 though.

3. Maybe I was not clear about this previously either, but it will use a strict ASCII value ordering of the files. That means that it sorts 0-9 first and then A-Z, so effectively 0123456789ABCDEFGHIJKMNOPQRSTUVWXYZ.

**Comment by ccchan234** [comment]
hi,
thx for reply.

1.
thx for intro to fsutil,
as a layman i use the teachings i found on internet

2. i'll stick with GUI and the .hex naming then, at the moment
I think i will stick to 4TB and 8TB HDD in near future.

thank you., i'll close the issue.
