### ISSUE TITLE
I encountered a problem

### ISSUE THREAD

**Issue by Keops10** [ArsenalRecon/Arsenal-Image-Mounter#27]
Hello
When I want to run Managed Source, I encounter the error in the picture, can you help me how to solve it?

**Comment by LTRData** [comment]
Yes, I will write a "how-to build" soon with some information about this. But in short:

The first message is just about the documentation project. You can ignore that, it is not required for building the dlls. It requires Sandcastle if you anyway want to build it.

The second problem is that the projects depend on a fork of DiscUtils that is not yet on NuGet (but will probably be soon). The fork source is here: https://github.com/LTRData/DiscUtils
You can build from that source and feed Arsenal Image Mounter build with the nuget package files you will get as output (add a local directory nuget search paths in visual studio nuget settings).

Hope this helps! There will otherwise soon be a major layout change to this project with all VB code converted to C# etc and I will try to make it only dependent on packages available through online repositories.

**Comment by Ladwaldez** [comment]
Thanks for the help. I will post the result here. yes I will look forward to the project going through C#.

**Comment by LTRData** [comment]
Quick update, the DiscUtils dependencies are now on NuGet and should be possible to restore automatically during Arsenal Image Mounter build process.

**Comment by Ladwaldez** [comment]
You're amazing my friend, thank you. We are waiting for the c# conversion for Arsenal Imager at this speed :)

**Comment by Ladwaldez** [comment]
I'm back, man. I'm getting this error what should I do to fix it.
https://ibb.co/4MHcBgX
https://ibb.co/KXQNqT7

**Comment by LTRData** [comment]
That is the old mount tool GUI application that is pretty much a proof-of-concept sample application that shows how to consume API etc. It is a bit limited, for example it does not use our generic write filter driver. For write-temporary operation it relies on support through the backend image file format provider. That means that for example vdi, vhdx etc where it can create a temporary differencing image is supported. Some old versions of libewf.dll also had a write-temporary feature. Raw/dd formats are not supported in write-temporary mode in that application.

You can however do that at command line:
`aim_cli --mount --filename=image.dd --writeoverlay=image.diff`

The next message, I would guess, is probably shown because you have a version of libewf.dll somewhere that is built without some required options. We have versions built with all options needed available in this repository.

The conversion of the code is mostly done but I need some more tests and coordinate it with some other changes and projects. It will probably arrive on GitHub in about a week.

**Comment by Ladwaldez** [comment]
I am using the libewf version from this repository. This error may be related to this version then. As far as I understand, there is no write support for images in E01 format in the current version.

**Comment by LTRData** [comment]
> I am using the libewf version from this repository. This error may be related to this version then. As far as I understand, there is no write support for images in E01 format in the current version.

It depends on what you want to do. If you want to create a new e01 image file from for example a hard drive, that is possible at command line:
`aim_cli --device=\\?\physicaldrive3 --saveas=D:\new_image.e01`

If you have an existing e01 image and you want to mount that in write-temporary mode:
`aim_cli --mount --filename=D:\new_image.e01` --writeoverlay=D:\new_image.diff`

It is not possible to modify an existing e01 image. That is by design. It is a forensics image format.

**Comment by Ladwaldez** [comment]
Hi https://github.com/laerciosimoes/ImageMount have you seen this thread. I'm looking forward to your C# version.

**Comment by Ladwaldez** [comment]
Could you please prepare a tool for me where I can mount only the E01 and EX01 extensions. It could be c# or vb.net. I want to integrate directly.

**Comment by LTRData** [comment]
If you then want to use the API for it from another application, I will prepare some examples together with next update of the repository here. But in general, the source for the command line tool shows roughly how it is done.

**Comment by Ladwaldez** [comment]
hello again, I saw that an image belonging to ubuntu is not mounted, how can I overcome this?

**Comment by LTRData** [comment]
> hello again, I saw that an image belonging to ubuntu is not mounted, how can I overcome this?

You mean _not mounted_ as in mounted, but you cannot see the files in Windows Explorer?

You can either use an ext file system driver for Windows to mount the Linux file system, or use our application in proffesonal mode to mount in "file system driver bypass mode".

There are probably other ways too. It is practically speaking like when you attach a physical Linux disk to a Windows machine.
