### ISSUE TITLE
aim_cli.exe --readonly mounts image as writable.

### ISSUE THREAD

**Issue by john-8998** [ArsenalRecon/Arsenal-Image-Mounter#47]
aim_cli.exe does not mount the image as read-only, at least for VMDK images.

This is the commandline I use:
aim_cli.exe --mount --readonly --online --filename="D:\MyDisk.vmdk" --provider=DiscUtils --background

**Comment by LTRData** [comment]
Thanks for reporting this! It seems to be an error in the message displayed when mounting, not that it really mounts it writable. We will correct this in next version!

**Comment by john-8998** [comment]
> Thanks for reporting this! It seems to be an error in the message displayed when mounting, not that it really mounts it writable. We will correct this in next version!

note that after mounting if that aim_cli.exe commandline, even if you open the GUI ArsenalImageMonter.exe in parallel, there it is indicated as writable... So it's not only error in the console message.

**Comment by LTRData** [comment]
> > Thanks for reporting this! It seems to be an error in the message displayed when mounting, not that it really mounts it writable. We will correct this in next version!
> 
> note that after mounting it with that aim_cli.exe commandline, even if you open the GUI ArsenalImageMonter.exe in parallel, there it is indicated as writable... So it's not only error in the console message.

Yes, I saw that too now, it detects it by read-only policy rather than checking whether it is really writable.

You can see this because when you mount an image in read only mode using aim_cli and run `chkdsk /f` on any of the volumes, you get an error message saying that the disk is not writable and the original image file is not modified. So, it is read only, it is just not shown properly.
