### ISSUE TITLE
AIM on XP

### ISSUE THREAD

**Issue by Virgus** [ArsenalRecon/Arsenal-Image-Mounter#5]
Hello again,
I tried to use AIM also on my XP SP3 and it works great except for the fact that I am obliged to avoid putting the PC into sleep state.

The problem seems to be with AIM as I get the following message: "System Standby Failed: The device driver For the 'SCSI/RAID Host Controller' device is preventing the machine from entering standby. Please close all applications and try again. If the problem persists, you may need to update this driver." I know that nowadays XP is mostly not supported but do you know if there's a registry tweak or something else to avoid this?

Meanwhile I'm continuing using ImDisk that is giving me some minor issues which I'd like to report, but I'd like to know: where exactly should I address them?

Thanks and have a nice weekend!
V.

**Comment by LTRData** [comment]
The XP version of AIM is based on older SCSI driver model that as far as I know does not support the necessary plug-and-play messages for supporting standby and hibernation. I don't think there is solution to that. For Server 2003 and Vista and newer, standby and hibernation are fully supported by design directly by the SCSI driver model we use.

ImDisk is discussed in a reboot pro forum. You can post your questions and ideas about it there.
http://reboot.pro/forum/59-imdisk

**Comment by Virgus** [comment]
Good to know, I could migrate to Server 2003 and keep XP-like interface. Thanks for both answers.

**Comment by EricZimmerman** [comment]
the risks of running xp or 2k3 far outweigh the advantages of newer OSs. get classicshell or start10 if you do not like the new interface =)

**Comment by Virgus** [comment]
Thanks Eric, I've seen that ClassicShell has improved a lot and I didn't know about Start10! Unfortunately in my case it's not just a problem of user interface, but I agree that these utilities may help a lot in the transition to newer OSs.
